//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phone_book
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phones
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public int ContactId { get; set; }
        public string Type { get; set; }
    
        public virtual Contacts Contacts { get; set; }
    }
}
